### ISSUE TITLE
Abstract push / showModal

### ISSUE THREAD

**Issue by erikpoort** [erikpoort/react-native-native-navigation#4]
Push and showModal are very similar, these should be abstracted one generic method.

**Comment by jmcur** [comment]
Now we have BaseNavigation (Which is extended from SingleNavigation and StackNavigation).
BaseNavigation has a method called registerScreens which receives the modalPath, the presentMethod (either push or showModal) and the showScreen object.

Then, on SingleNavigation we have:
```
showModal = (showScreen) => {
		return super.registerScreens(`${this.screenID}/modal`, ReactNativeNativeNavigation.showModal, showScreen);
	}
```

And in StackNavigation:
```
push = (showScreen) => {
		return super.registerScreens(`${this.screenID}`, ReactNativeNativeNavigation.push, showScreen);
	}
```
