### ISSUE TITLE
Lazy load flags

### ISSUE THREAD

**Issue by erikpoort** [erikpoort/react-native-native-navigation#6]
You should be able to set a lazy-load flag.
Example: When initiating the app with a 3 page step, you should be able to specify if all three components should me started, or just the latest, loading the other two when they become visible.

**Comment by jmcur** [comment]
This is working on iOS, but it wasn't developed (neither tested) on Android side.

**Comment by jmcur** [comment]
This need to be changed. The lazyLoad flag is a string now ('true' or 'false'). It should be a boolean ({true} or {false}).
